# ============================================
# Fail2ban Filter - Laravel Login
# ============================================

[Definition]

failregex = ^.*Login failed ip=<HOST>.*$
            ^.*authentication failed from <HOST>.*$
            ^.*Too Many Attempts from <HOST>.*$
            ^.*Unauthorized from <HOST>.*$
            ^.*401 from <HOST>.*$
            ^.*429 from <HOST>.*$

ignoreregex =
